services:

  nginx:
    image: nginx:1.25
    ports:
      - '8001:80'
    volumes:
      - ./app:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www
